### ISSUE TITLE
Missing cache language string

### ISSUE THREAD

**Issue by KineoMichaelT** [branchup/moodle-filter_shortcodes#1]
Typically cache definitions have a language string defined in the lang pack for plug-ins with caches.
It looks like this plug-in is missing an appropriate language string for the 'handlers' cache.

$string['cachedef_handlers'] should be defined in the language pack - maybe just as 'Shortcode handlers'?

**Comment by FMCorz** [comment]
That's a very good point, thank you for sharing!
