### ISSUE TITLE
Prepare for PHPUNIT 9

### ISSUE THREAD

**Issue by iplusacademy** [branchup/moodle-filter_shortcodes#2]
The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageMatches() instead.

I made a [commit](https://github.com/iplusacademy/moodle-filter_shortcodes/commit/2714aab31b6e68dc0326137a7d122c1396c35199) that fixes the problem in MOODLE_39_STABLE+ and the [workflow](https://github.com/iplusacademy/moodle-filter_shortcodes/runs/2430592294?check_suite_focus=true#step:15:1) proves it is fixed.

**Comment by FMCorz** [comment]
Thank you for the report, this was addressed using your commit ccec189262695b77b4a4c808f5145f1d5457ec4d. Thank you!
